[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "fil-proofs-tooling",
]

[patch.crates-io]
bellperson = { git = "https://github.com/filecoin-project/bellman.git", branch = "feat/prove-many" }
