[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "fil-proofs-tooling",
]

[patch.crates-io]
#bellperson = { git = "https://github.com/finalitylabs/bellman", branch="fil-lock" }
bellperson = { git = "https://github.com/vmx/bellman", branch="gpu-lock-plus-fixes" }
#bellperson = { git = "https://github.com/vmx/bellman", branch="gpu-lock" }
